[15.0][ADD] fieldservice_equipment_note
solvosci/slv-field-service pull request #19
Opened 2023-05-16 06:33 UTC by LucPinheiro

@ChristianSantamaria

2023-05-16 14:47 UTC, ChristianSantamaria requested changes
Some improvements:

2023-05-16 14:47 UTC, ChristianSantamaria commented on fieldservice_equipment_note/__manifest__.py
> +    "depends": ["fieldservice", "fieldservice_sale_reference"],
```suggestion
    "depends": ["fieldservice_sale_reference"],
```

2023-05-16 14:47 UTC, ChristianSantamaria commented on fieldservice_equipment_note/__manifest__.py
> +        Add new fields in the fsm order models.
```suggestion
        Adds new model to have equipment observations in each fsm.order.
```
Also change readme/description
Generate Readme again with new changes

2023-05-18 11:36 UTC, ChristianSantamaria requested changes
The last fixes:

2023-05-18 11:36 UTC, ChristianSantamaria commented on fieldservice_equipment_note/reports/i18n/es.po
> +# Translation of Odoo Server.
This folder was moved place put it where it belongs

2023-05-18 11:36 UTC, ChristianSantamaria commented on fieldservice_equipment_note/README.rst
> +    :alt: solvosci/slv-field-service-actualizado
The same as in the other PR
```suggestion
    :alt: solvosci/slv-field-service
```

2023-05-19 13:00 UTC, dalonsod commented
@LucPinheiro tested and made several changes (see https://github.com/solvosci/slv-field-service/pull/19/commits/ff40832f8e978c1541b17e81d795fa3ea3dd0fa7 for check differences), please analyze and test them:

- Removed manifest dependency with `fieldservice_sale_reference` and made addon only dependent on `fieldservice`. Also removed `sale_reference` fields usages (*).
- Added description for `fsm.equipment.note` model.
- In general I've moved "Observation" typo to more correct "note", even in field definitions.
- For FSM Order, renamed `fsm_equipment_ids` by a more accurate `fsm_equipment_note_ids` name.
- Some translations adjustments. Removed `i18n` folder inside reports folder.
- Remove unnecessary `create="1"` in equipment notes tree inline view. Removed duplicated `editable="bottom"`.

(*) This change is due to separate functionality in tho different addons. Once `fieldservice_equipment_note` is ready, we should create a `fieldservice_equipment_note_sale_reference` addon that adds the `sale_reference` usages previously removed. We should add this new addon in another commit in this PR, and task will be finished

2023-05-22 15:34 UTC, dalonsod approved these changes
Functionality finally splitted in two addons, ready to be merged. Let's go...

2023-05-22 15:35 UTC, merged