[15.0][IMP] fieldservice_person_salary: move column Planning on report fsm.order
solvosci/slv-field-service pull request #21
Opened 2023-05-18 11:22 UTC by LucPinheiro

@ChristianSantamaria 
@dalonsod

2023-05-18 11:33 UTC, ChristianSantamaria requested changes
Fix Name commit 
You should start working on the current version of the repository itself so as not to have problems with the names for this slv-field-service-actualizado

Some improvements:

2023-05-18 11:33 UTC, ChristianSantamaria commented on fieldservice_person_salary/README.rst
> +    :alt: solvosci/slv-field-service-actualizado
```suggestion
    :alt: solvosci/slv-field-service
```

This is in several places, we have to solve it too

2023-05-18 11:33 UTC, ChristianSantamaria commented on fieldservice_person_salary/README.rst
> +* Christian Santamaría <christian.santamaria@solvos.es>
Me?

2023-05-18 11:33 UTC, ChristianSantamaria commented on fieldservice_person_salary/__manifest__.py
> +    "depends": ["fieldservice", "fieldservice_sale_reference"],
```suggestion
    "depends": ["fieldservice_sale_reference"],
```

2023-05-18 11:39 UTC, dalonsod requested changes

2023-05-18 11:39 UTC, dalonsod commented on fieldservice_person_salary/views/fsm_order_salary_views.xml
> +
Please remove this change

2023-05-18 11:39 UTC, dalonsod commented on fieldservice_person_salary/views/fsm_order_views.xml
> -
Please remove this change (that blank should be removed, but better not in this commit, since this file is not linked with any required change)

2023-05-18 11:42 UTC, dalonsod commented
> Fix Name commit

Yes, commit and PR messages should be basically the same (with `[15.0]` addition in PR). Current name is right for temporary branch name, anyway.

2023-05-18 12:21 UTC, LucPinheiro commented on fieldservice_person_salary/README.rst
> +* Christian Santamaría <christian.santamaria@solvos.es>
yes

2023-05-22 16:23 UTC, dalonsod commented
Made squash and minor changes. Removed unnecessary `fieldservice_sale_reference` manifest dependency. Let's merge...

2023-05-22 16:24 UTC, merged