[15.0][IMP] fieldservice_sale_reference: add sale_reference in fsm.order report
solvosci/slv-field-service pull request #9
Opened 2023-04-28 06:49 UTC by ChristianSantamaria

Add sale_reference in reports:
![imagen](https://user-images.githubusercontent.com/22427989/235075068-4eeea2bd-8063-4a9e-b125-bf73714e4559.png)

2023-04-28 07:25 UTC, dalonsod requested changes
See comment.
And add yourself to CONTRIBUTORS

2023-04-28 07:25 UTC, dalonsod commented on fieldservice_sale_reference/reports/fsm_order_template.xml
> +            <span> - <span t-field="doc.sale_reference" /></span>
Empty data protection (not tested):
```suggestion
            <t t-if="doc.sale_reference">
                <span> - <span t-field="doc.sale_reference" /></span>
            </t>
```

2023-04-28 07:32 UTC, ChristianSantamaria commented
Done and I am the only contributor of this addon

2023-04-28 08:18 UTC, dalonsod commented
OK, I'll test it ASAP

2023-04-28 11:04 UTC, dalonsod approved these changes
Locally tested 👍 

@ChristianSantamaria you can merge it 😀

2023-05-02 06:15 UTC, ChristianSantamaria commented
Let goo!

2023-05-02 06:15 UTC, merged